language: cpp

matrix:
  include:
    - os: windows
      env: BUILD_CONFIGURATION=Debug
    - os: windows
      env: BUILD_CONFIGURATION=Release
    - os: linux
      dist: trusty
      group: travis_lts
      sudo: required
      env: BUILD_CONFIGURATION=Debug
    - os: linux
      dist: trusty
      group: travis_lts
      sudo: required
      env: BUILD_CONFIGURATION=Release
    - os: osx
      osx_image: xcode9.1
      env: BUILD_CONFIGURATION=Debug
    - os: osx
      osx_image: xcode9.1
      env: BUILD_CONFIGURATION=Release

before_install:
  - . .travis/before-install.sh

install:
  - . .travis/install.sh

script:
  - . .travis/lint.sh
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION ../
  - cmake --build .
